---
format_version: 10
environments:
  gocd:
    pipelines:
      - cds
pipelines:
  cds:
    group: gocd
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      cds-integration:
        git: https://github.com/vishnuvardhanmaari/actions.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - cds-integration:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            deployment:
              timeout: 0
              resources:
                - gocd
